/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenSol from "./Token.sol";
export { Ballot__factory } from "./Ballot__factory";
export { BankAccount__factory } from "./BankAccount__factory";
